### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by ezajesen** [lemonsprite/Pustaka-Booking#3]
buka menu adminnya gimana

**Comment by lemonsprites** [comment]
login dulu

**Comment by lemonsprites** [comment]
demo user: 
email -> admin@admin.com
pass -> admin

klo yang dimaksud dashboard admin, app nya emang gk dibikin dashboard admin. jadi role admin nya disamakan kayak role user buat demo booking + ngeranjangin buku✔️
